# iOS Podfile for KsanniApp
platform :ios, '14.0'
use_frameworks!

target 'KsanniApp' do
  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  
  # Google Sign-In
  pod 'GoogleSignIn'
  
  # Additional utilities
  pod 'Alamofire', '~> 5.6'
  
  target 'KsanniAppTests' do
    inherit! :search_paths
  end
  
  target 'KsanniAppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end