name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.gitattributes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;35.0.0"

      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Assemble debug APK
        run: ./gradlew --no-daemon :app:assembleDebug --stacktrace --warning-mode all

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app/build_android3/outputs/apk/debug/*.apk
            app/build/outputs/apk/debug/*.apk
