name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;35.0.0"

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build release APK and AAB
        run: |
          ./gradlew --no-daemon clean :app:assembleRelease :app:bundleRelease --stacktrace --info

      - name: Verify APK/AAB exist
        run: |
          echo "Listing app/build_android3/outputs/apk/release" && ls -la app/build_android3/outputs/apk/release || true
          echo "Listing app/build/outputs/apk/release" && ls -la app/build/outputs/apk/release || true
          echo "Listing app/build_android3/outputs/bundle/release" && ls -la app/build_android3/outputs/bundle/release || true
          echo "Listing app/build/outputs/bundle/release" && ls -la app/build/outputs/bundle/release || true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build_android3/outputs/apk/release/app-release.apk
            app/build_android3/outputs/apk/release/app-release-unsigned.apk
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
            app/build_android3/outputs/bundle/release/app-release.aab
            app/build/outputs/bundle/release/app-release.aab
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
