name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;35.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew --no-daemon clean :app:assembleRelease

      - name: Verify APK exists
        run: ls -la app/build_android3/outputs/apk/release || ls -la app/build/outputs/apk/release

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build_android3/outputs/apk/release/app-release.apk
            app/build/outputs/apk/release/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
