name: Build and Release Debug APK (manual only)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Optional tag name to use for the release (defaults to v<run_number>-debug for manual runs)'
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;35.0.0"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --info --no-daemon

      - name: Upload artifact (debug APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app/build_android3/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/app-debug.apk

      - name: Decide tag name (manual runs only)
        if: github.event_name == 'workflow_dispatch'
        id: tag
        run: |
          INPUT_TAG="${{ github.event.inputs.tag_name }}"
          if [[ -z "$INPUT_TAG" ]]; then
            INPUT_TAG="v${GITHUB_RUN_NUMBER}-debug"
          fi
          echo "tag_name=$INPUT_TAG" >> $GITHUB_OUTPUT
      - name: Create GitHub Release (manual only)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          target_commitish: ${{ github.sha }}
          files: |
            app/build_android3/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/app-debug.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
